services:
  backend:
    container_name: nodejs-backend-container
    build: ./server
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure:3
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - ./server/example.env
    develop:
      watch: 
        - path: ./server
          action: sync
          ignore: 
            - node_modules
            - .git/
          target: /app
        - path: ./server/package.json
          action: rebuild
        - path: ./server/tsconfig.json
          action: rebuild
        - path: ./server/src/index.ts
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
  postgres:
    container_name: postgres-db-container
    image: postgres:14.1-alpine
    restart: on-failure:3
    env_file:
      - ./server/example.env
    ports:
      - "5432:5432"
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./server/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 15s
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./client
          action: sync
          ignore:
          - node_modules
          - .git/
          target: /app
        - path: ./client/package.json
          action: rebuild
    ports:
      - 5173:5173
    depends_on:
      - backend

