services:
  backend:
    container_name: nodejs-backend-container
    build: ./nodejs-backend
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure:3
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    env_file:
   
      - ./.env
    develop:
      watch: 
        - path: ./nodejs-backend
          action: rebuild
          ignore: 
            - node_modules
            - .git/
          target: /usr/src/app
        - path: ./nodejs-backend/package.json
          action: rebuild
        - path: ./nodejs-backend/tsconfig.json
          action: rebuild
        - path: ./docker-compose-nodejs.yml
          action: rebuild
  postgres:
    container_name: postgres-db-container
    image: postgres:14.1-alpine
    restart: on-failure:3
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      # When the PostgresSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./nodejs-backend/database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 15s

