name: "nodejs-project-development"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: pg-db
    ports:
      - 5432:5432
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    restart: unless-stopped
    develop:
      watch: 
        - path: ./server
          action: sync
          ignore: 
            - node_modules
            - .git/
          target: /app
        - path: ./server/package.json
          action: rebuild
        - path: ./docker-compose.yml
          action: rebuild
    ports:
      - 5000:5000
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U root -d pg-db"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 15s
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./client
          action: sync
          ignore:
          - node_modules
          - .git/
          target: /app
        - path: ./client/package.json
          action: rebuild
    ports:
      - 5173:5173