
# requires vs code REST Client extension
# I perfer it over Postman cause of some bugs I'm experiencing with it
# also it feels better to centralize api tests in a single file

# root's password is 12432543234
# jim's password is 1242353453234
# bill's password is 24325
# bob's password is 252453
# gamer's password is 442232
@port = 5001
###
# GET all users
GET http://localhost:{{port}}/users

###
POST http://localhost:{{port}}/authentication
Content-Type: application/json

{
  "username": "root",
  "password": "12432543234"
}
###

POST http://localhost:{{port}}/authentication
Content-Type: application/json

{
  "username": "jim",
  "password": "1242353453234"
}
###

#
