
# requires vs code REST Client extension
# I perfer it over Postman cause of some bugs I'm experiencing with it
# also it feels better to centralize api tests in a single file

###
# GET a note
GET http://localhost:5000/data/Example Title

###
# GET all notes
GET http://localhost:5000/data

###
POST http://localhost:5000/data/Example Title
Content-Type: application/json

{
    "text": "<p class=\"editor-paragraph\"><span style=\"white-space: pre-wrap;\">blah blah blah BLAH.</span></p>"

}

###
PATCH http://localhost:5000/data/Example Title
Content-Type: application/json

{
    "text": "<p class=\"editor-paragraph\"><span style=\"white-space: pre-wrap;\">Different kind of blah blah blah BLAH.</span></p>"

}

###


DELETE http://localhost:5000/data/Example Title

###