
# requires vs code REST Client extension
# I perfer it over Postman cause of some bugs I'm experiencing with it
# also it feels better to centralize api tests in a single file
@port = 5001
###
# GET a user
GET http://localhost:{{port}}/users/bubba

###
# GET all users
GET http://localhost:{{port}}/users

###
POST http://localhost:{{port}}/users
Content-Type: application/json

{
  "username": "bubba",
  "email": "bubba@exampledomain.com",
  "role": "user"

}

###

DELETE http://localhost:{{port}}/users/bubba

###
PATCH http://localhost:{{port}}/users/bubba
Content-Type: application/json

{
  "email": "bubba02@exampledomain.com"
}
###